### ISSUE TITLE
Problem with curl request

### ISSUE THREAD

**Issue by rafaelcabreu** [mcueto/djangorestframework-auth0_sample#3]
Hello, first of all thanks for the effort you put into this. I'm a beginner with auth0 and token authentication and I'm having some trouble with the sample code you provided and would appreciate some insight on my problem. 
I've created an auth0 account and a API with the following audience "http://localhost:8000/api/" and then used the client id and client secret for the client that was created with my api in settings.py file. Then, i used the access_token from the "Test" tab in the api section in the cURL command bellow:

`curl -X POST -H 'Content-Type: application/json' -H 'Authorization:JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL29yYWN1bG9tZXRlb3JvbG9naWEuYXV0aDAuY29tLyIsInN1YiI6IlpKQ3RXQURKdkhlQUtXNFZkcmFyN2FLSnQyd1h5ajI1QGNsaWVudHMiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpLyIsImV4cCI6MTUwMDkzNjgwOSwiaWF0IjoxNTAwODUwNDA5LCJzY29wZSI6IiJ9.hIOuXZovuvQzcjePtMIiuH3NihMqVAiyQE4ggaqTsfQ ' -d '{"text":"New todo"}' http://localhost:8000/api/todos/`

However the api response that I get is  "POST /api/todos/ HTTP/1.1" 401 33 and the following json: {"detail":"Invalid Client Code."}. I'm probably missing something really simples but the auth0 documentation is so overwhelming. Could you please point me in the right direction? I don't know if there is something wrong with my auth0 configuration or if i need a different token for the api request.

Thanks in advance.
Rafael

**Comment by mcueto** [comment]
Hi @rafaelcabreu what's the scope that you're using in your frontend client app?(that gets the token) maybe there are some data that are not retrieved. The *aud* need to be the same that the client_id in your django settings, otherwise i won't work at all.

You can debug your token in https://jwt.io/ in order to verify if it's a token problem or a software configuration(in rest_framework_auth0) problem.

**Comment by bholagabbar** [comment]
@rafaelcabreu @mcueto This library is heavily outdated and non-functional. I have taken help from the official auth-0 docs at https://auth0.com/docs/quickstart/backend/python and added support for Auth0 token validation as Django Middleware. You can see the post at https://community.auth0.com/questions/8640/auth0-token-validation-as-django-middleware
